[project]
version = "0.2.0"
name = "oceandata-notebooks"
description = "Oceandata Jupyter Notebook Tutorials"
urls.Issues = "https://github.com/gsfc-oel/oceandata-notebooks/issues"
urls.Repository = "https://github.com/gsfc-oel/oceandata-notebooks"
license.text = "Apache-2.0"
requires-python = ">=3.9"
readme = "README.md"
maintainers = [
  { "name" = "Ian Carroll", "email" = "ian.t.carroll@nasa.gov" },
]
dependencies = [
  # every package used in an import or by a backend (e.g. h5netcdf)
  # TODO: torch, torchvision
  "cartopy>=0.22.0",
  "cmocean>=4.0.3",
  "dask[distributed]>=2024.4.1",
  "earthaccess>=0.11.0",
  "h5netcdf>=1.3.0",
  "holoviews>=1.19.1",
  "hvplot>=0.9.2",
  "matplotlib>=3.8.4",
  "netcdf4>=1.6.5",
  "numba>=0.60.0",
  "pandas>=2.2.1",
  "pillow>=10.4.0",
  "pvlib>=0.11.1",
  "pyproj>=3.6.1",
  "scipy>=1.13.1",
  "seaborn>=0.13.2",
  "tqdm>=4.66.5",
  "xarray>=2024.3.0",
]
optional-dependencies.kernel = [
  # additional packages for book/setup.py
  "bash-kernel>=0.9.3",
  "ipykernel>=6.29.3",
  "ipywidgets>=8.1.2",
]
optional-dependencies.docker = [
  # additional packages for book/setup.py
  # TODO: async-timeout is a possible unlisted dep of jupyter-vscode-proxy?
  "async-timeout>=4.0.3",
  "bash-kernel>=0.9.3",
  "black>=24.10.0",
  "boto3>=1.35.36",
  "dask-gateway>=2024.1.0",
  "dask-labextension>=7.0.0",
  "geopandas>=1.0.1",
  "geoviews>=1.12.0",
  "gh-scoped-creds>=4.1",
  "isort>=5.13.2",
  "jupyter-vscode-proxy>=0.6",
  "jupyterlab-code-formatter>=3.0.2",
  "jupyterlab-git>=0.50.1",
  "jupyterlab-h5web>=12.3.0",
  "jupytext>=1.16.4",
  "lz4>=4.3.3",
  "pyinterp>=2024.6.0",
  "rasterio>=1.4.2",
  "rioxarray>=0.15.0",
  "scikit-image>=0.24.0",
  "scikit-learn>=1.5.2",
  "uv>=0.4.27",
  "zarr>=2.18.2",
]

[dependency-groups]
dev = [
  "jupyter-book>=1.0.3",
  "jupyter-repo2docker>=2024.7.0",
  "pre-commit>=4.0.1",
  "ruff>=0.7.1",
]

[tool.jupytext]
formats = { "notebooks" = "ipynb", "src" = "py" }
notebook_metadata_filter = "-all,jupytext,language_info.name"
cell_metadata_filter = "all,-trusted"

[tool.ruff.lint]
extend-select = ["I", "D"]
ignore = ["D1", "D417", "F841"] # TODO: reconsider F841

# [tool.uv]
#   index-strategy = "unsafe-best-match"
#   extra-index-url = ["https://download.pytorch.org/whl/cpu"]
