name: build jupyterhub image
on:
  push:
    paths:
      - .github/workflows/repo2docker.yaml
      - docker/**
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: free space on runner
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        docker-images: false
    - name: checkout files in repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: docker
        sparse-checkout-cone-mode: false
    - name: move repo2docker files
      run: |
        mv docker/* .
        rmdir docker
        ls
    - name: build with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: ghcr.io
        APPENDIX_FILE: appendix
        FORCE_REPO2DOCKER_VERSION: jupyter-repo2docker==2024.7.0
